src/objects/C501_Appointment__c.object
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/C501_Appointment__c/fields/Appointment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appointment Schedule</label>
    <referenceTo>C501_Appointment_Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/C501_Appointment__c/fields/Available_Time__c.field-meta.xml
<CustomField>
    <fullName>Available_Time__c</fullName>
    <label>Available Time</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/C501_Appointment__c/fields/Maximum_Scheduled_Appointments__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Scheduled_Appointments__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Maximum Scheduled Appointments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/C501_Appointment__c/fields/Name_Unique__c.field-meta.xml
<CustomField>
    <fullName>Name_Unique__c</fullName>
    <description>Unique Name to prevent more than 1 appointment for same day and time</description>
    <label>Name Unique</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/C501_Appointment__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

src/objects/C501_Appointment_Schedule__c.object
<CustomObject>
    <label>Appointment Schedule</label>
    <nameField>
        <label>Appointment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/C501_Appointment_Schedule__c/fields/Days_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Days_of_Week__c</fullName>
    <label>Days of Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/C501_Appointment_Schedule__c/fields/Number_Appointments_per_15_min_interval__c.field-meta.xml
<CustomField>
    <fullName>Number_Appointments_per_15_min_interval__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Maximum number of households available to sign-up per 15 minute interval.</description>
    <inlineHelpText>Maximum number of households available to sign-up per 15 minute interval.</inlineHelpText>
    <label>Number Appointments per 15 min interval</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/C501_Appointment_Schedule__c/fields/Range_Of_Recurrence_End_By__c.field-meta.xml
<CustomField>
    <fullName>Range_Of_Recurrence_End_By__c</fullName>
    <label>Range of Recurrence End By</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/C501_Appointment_Schedule__c/fields/Scheduled_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_End_Time__c</fullName>
    <label>Scheduled End Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

src/main/default/objects/C501_Appointment_Schedule__c/fields/Scheduled_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Start_Date_Time__c</fullName>
    <label>Scheduled Start Date &amp; Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/C501_Appointment_Schedule__c/fields/Senior_Only_Appointments_60_and_over__c.field-meta.xml
<CustomField>
    <fullName>Senior_Only_Appointments_60_and_over__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Senior Only Appointments (60 and over)</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/C501_Appointment_Schedule__c/fields/Weekly_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Occurrence__c</fullName>
    <label>Weekly Occurrence</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st</fullName>
            </value>
            <value>
                <fullName>2nd</fullName>
            </value>
            <value>
                <fullName>3rd</fullName>
            </value>
            <value>
                <fullName>4th</fullName>
            </value>
            <value>
                <fullName>5th</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/C501_AppointmentScheduleTriggerHelper.cls
public with sharing class C501_AppointmentScheduleTriggerHelper {

	public class InvalidParameterValueException extends Exception {}

	// only need one instance of this class per transaction
	private static C501_AppointmentScheduleTriggerHelper instance;
	public static C501_AppointmentScheduleTriggerHelper get() {
		if (instance == null) instance = new C501_AppointmentScheduleTriggerHelper();
		return instance;
	}
	
	public void updateAppointmentSchedule( List<C501_Appointment_Schedule__c> appointmentScheduleList, map<id, C501_Appointment_Schedule__c> oldMap, Boolean isBefore) {

		if (appointmentScheduleList == null || appointmentScheduleList.isEmpty()) {
			return;
		}

		if (isBefore) {
			for (C501_Appointment_Schedule__c appointmentSchedule :appointmentScheduleList) {

				System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule - isBefore Scheduled_Start_Date_Time__c (Time): ' + appointmentSchedule.Scheduled_Start_Date_Time__c.time() + ' Scheduled_End_Time__c: ' + appointmentSchedule.Scheduled_End_Time__c);
				if (appointmentSchedule.Scheduled_Start_Date_Time__c.time() >= appointmentSchedule.Scheduled_End_Time__c) {
					System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule - add error');
					appointmentSchedule.AddError('updateAppointmentSchedule::Exception Start Time (' + appointmentSchedule.Scheduled_Start_Date_Time__c.time() + ') must be less than End Time (' + appointmentSchedule.Scheduled_End_Time__c + ')');
					continue;					
				}

				System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule - isBefore Scheduled_Start_Date_Time__c (Date): ' + appointmentSchedule.Scheduled_Start_Date_Time__c.date() + ' Range_Of_Recurrence_End_By__c: ' + appointmentSchedule.Range_Of_Recurrence_End_By__c);
				if (appointmentSchedule.Scheduled_Start_Date_Time__c.date() > appointmentSchedule.Range_Of_Recurrence_End_By__c) {
					System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule - add error');
					appointmentSchedule.AddError('updateAppointmentSchedule::Exception Start Date (' + appointmentSchedule.Scheduled_Start_Date_Time__c.date() + ') must be less or equal to the End Date (' + appointmentSchedule.Range_Of_Recurrence_End_By__c + ')');
					continue;					
				}
			}
		}

		//
		// Perform all SOQL Queries outside of loop to avoid Salesforce Governor Limits: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_gov_limits.htm
		//
		Date dateToday = system.today();
		List<C501_Appointment__c> allAppointments = [
			SELECT Id, Name, Appointment_Schedule__c, Enable__c, Maximum_Scheduled_Appointments__c
			FROM C501_Appointment__c
			WHERE Date__c >= :dateToday];

		// Process all appointments to make sure appointments have the right parent
		List<C501_Appointment_Schedule__c> allAppointmentSchedules = [
			SELECT Id, Name, Enable__c, Scheduled_Start_Date_Time__c, Scheduled_End_Time__c, Range_Of_Recurrence_End_By__c, Days_of_Week__c, Weekly_Occurrence__c,
				Number_Appointments_per_15_min_interval__c, Senior_Only_Appointments_60_and_over__c
			FROM C501_Appointment_Schedule__c
			WHERE Enable__c = true AND isDeleted = false
			ORDER BY LastModifiedDate DESC];

		// Step1: Remove Schedule Id
		Map<String, C501_Appointment__c> allAppointmentsByName = new Map<String, C501_Appointment__c>();
		Map<Id, C501_Appointment__c> updateAppointments = new Map<Id, C501_Appointment__c>();
		for ( C501_Appointment__c appointment:allAppointments) {
			try {
				appointment.Appointment_Schedule__c = null;
				updateAppointments.put(appointment.Id, appointment);

				// Build ByName map for processing later
				allAppointmentsByName.put(appointment.Name, appointment);
			}
			catch (Exception e) {
				appointmentScheduleList[0].AddError('updateAppointmentSchedule::Exception - ' + String.valueOf(e));
				continue;
			}
		}

		// Perform all DML (Data Manipulation Language) calls (insert, update, merge, delete, restore) outside of loop to avoid Salesforce Governor Limits: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_gov_limits.htm
		if (!updateAppointments.isEmpty()) {
			update updateAppointments.values();
		}

		updateAppointments.clear();
		Map<String, C501_Appointment__c> insertAppointments = new Map<String, C501_Appointment__c>();

		// Step2: Update all related Appointments and create new Appointments
		for ( C501_Appointment_Schedule__c appointmentSchedule :allAppointmentSchedules ) {

			if (!appointmentSchedule.Enable__c) {
				continue;
			}

			System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule - appointmentSchedule: ' + appointmentSchedule);

			try {
				DateTime appointmentDateTime = appointmentSchedule.Scheduled_Start_Date_Time__c;

				Set<DateTime> appointmentDays = new Set<DateTime>();
				appointmentDays.add(appointmentDateTime);

				while (appointmentSchedule.Range_Of_Recurrence_End_By__c != null &&
					appointmentDateTime.date() <= appointmentSchedule.Range_Of_Recurrence_End_By__c) {

					// Set appointmentDateTime to first day of the month
					appointmentDateTime = appointmentDateTime.addDays(-1 * (appointmentDateTime.day() - 1));

					for ( Integer weekday = 0; weekday <= 6; weekday++ ) {

						String dayOfWeek = appointmentDateTime.format('E');
						System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule dayOfWeek: ' + dayOfWeek + ' appointmentSchedule.Days_of_Week__c: ' + appointmentSchedule.Days_of_Week__c);

						if (appointmentSchedule.Days_of_Week__c.contains(dayOfWeek)) {
							for ( String weeklyOccurence :appointmentSchedule.Weekly_Occurrence__c.split(';')) {

								Integer weeklyOccuranceFactor = Integer.valueOf(weeklyOccurence.left(1)) - 1;
								DateTime appointmentDayAdd = appointmentDateTime.addDays(7 * weeklyOccuranceFactor);

								System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule weeklyOccurence Loop: weeklyOccurence' + weeklyOccurence + ' weeklyOccuranceFactor: ' + String.valueOf(weeklyOccuranceFactor) + ' appointmentDayAdd: ' + appointmentDayAdd.format());

								System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule ' + appointmentDayAdd + ' >= ' + appointmentSchedule.Scheduled_Start_Date_Time__c);
								System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule ' + appointmentDayAdd.month() + ' == ' + appointmentDateTime.month());

								if (appointmentDayAdd >= appointmentSchedule.Scheduled_Start_Date_Time__c
									&& appointmentDayAdd.month() ==  appointmentDateTime.month()) {

									System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule add appointmentDayAdd: ' + appointmentDays);
									appointmentDays.add(appointmentDayAdd);
								}						
							}
						}

						appointmentDateTime = appointmentDateTime.addDays(1);
					}

					// Set appointmentDateTime to next month
					appointmentDateTime = appointmentDateTime.addMonths(1);
				}

				for (DateTime appointment :appointmentDays) {

					System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule appointment: ' + appointment);

					System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule ' + appointment.date() + ' < ' + dateToday);

					// Skip processing times that are in the past
					if (appointment.date() < dateToday) {
						continue;
					}

					appointmentDateTime = appointment;

					// Salesforce Apex DateTime Rounding Error - make sure starting on same start hour
					appointmentDateTime = appointmentDateTime.addHours(appointmentSchedule.Scheduled_Start_Date_Time__c.hour() - appointmentDateTime.hour());

					System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule while (' + appointmentDateTime.time() + ' < ' + appointmentSchedule.Scheduled_End_Time__c + ')');

					while (appointmentDateTime.time() < appointmentSchedule.Scheduled_End_Time__c) {
						String appointmentName = appointmentDateTime.format('yyyy-MM-dd - hh:mm a');
						String appointmentTimeDisplay = appointmentDateTime.format('hh:mm a');

						System.debug(LoggingLevel.DEBUG, '*****C501_AppointmentScheduleTriggerHelper::updateAppointmentSchedule Check Appointment - appointmentTimeDisplay: ' + appointmentTimeDisplay + ' Name: ' + appointmentName);

						if (allAppointmentsByName.containsKey(appointmentName)) {

							C501_Appointment__c appointmentUpdate = allAppointmentsByName.get(appointmentName);
							if (!updateAppointments.containsKey(appointmentUpdate.Id)) {
								
								appointmentUpdate.Appointment_Schedule__c = appointmentSchedule.Id;
								appointmentUpdate.Available_Time__c = appointmentDateTime;
								appointmentUpdate.Date__c = appointmentDateTime.date();
								appointmentUpdate.Time__c = appointmentTimeDisplay;

								appointmentUpdate.Appointment_Schedule__c = appointmentSchedule.Id;
								appointmentUpdate.Maximum_Scheduled_Appointments__c = appointmentSchedule.Number_Appointments_per_15_min_interval__c;
								appointmentUpdate.Senior_Only_Appointments_60_and_over__c = appointmentSchedule.Senior_Only_Appointments_60_and_over__c;

								updateAppointments.put(appointmentUpdate.Id, appointmentUpdate);
							}
						}
						else {
							C501_Appointment__c appointmentScheduling = new C501_Appointment__c(
								Name = appointmentName,
								Name_Unique__c = appointmentName,
								Appointment_Schedule__c = appointmentSchedule.Id,
								Available_Time__c = appointmentDateTime,
								Date__c = appointmentDateTime.date(),
								Time__c = appointmentTimeDisplay,
								Enable__c = true,
								Maximum_Scheduled_Appointments__c = appointmentSchedule.Number_Appointments_per_15_min_interval__c,
								Senior_Only_Appointments_60_and_over__c = appointmentSchedule.Senior_Only_Appointments_60_and_over__c);

							insertAppointments.put(appointmentName, appointmentScheduling);
						}

						// Increment by 15 minutes
						appointmentDateTime = appointmentDateTime.addMinutes(15);
					}
				}
			}
			catch (Exception e) {
				appointmentScheduleList[0].AddError('updateAppointmentSchedule::Exception - ' + String.valueOf(e));
				continue;
			}
		}

		// Perform all DML (Data Manipulation Language) calls (insert, update, merge, delete, restore) outside of loop to avoid Salesforce Governor Limits: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_gov_limits.htm
		if (!updateAppointments.isEmpty()) {
			update updateAppointments.values();
		}
		if (!insertAppointments.isEmpty()) {
			insert insertAppointments.values();
		}
	}
}