src/objects/C501_Appointment__c.object
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/C501_Appointment__c/fields/Appointment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appointment Schedule</label>
    <referenceTo>C501_Appointment_Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/C501_Appointment__c/fields/Available_Time__c.field-meta.xml
<CustomField>
    <fullName>Available_Time__c</fullName>
    <label>Available Time</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/C501_Appointment__c/fields/Maximum_Scheduled_Appointments__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Scheduled_Appointments__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Maximum Scheduled Appointments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/C501_Appointment__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

src/objects/C501_Appointment_Schedule__c.object
<CustomObject>
    <label>Appointment Schedule</label>
    <nameField>
        <label>Appointment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/C501_Appointment_Schedule__c/fields/Number_Appointments_per_15_min_interval__c.field-meta.xml
<CustomField>
    <fullName>Number_Appointments_per_15_min_interval__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Maximum number of households available to sign-up per 15 minute interval.</description>
    <inlineHelpText>Maximum number of households available to sign-up per 15 minute interval.</inlineHelpText>
    <label>Number Appointments per 15 min interval</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/C501_Appointment_Schedule__c/fields/Number_Appointments_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Number_Appointments_per_Month__c</fullName>
    <description>Maximum number of appointments a household can have in a month to be available to sign-up for this appointment.</description>
    <inlineHelpText>Maximum number of appointments a household can have in a month to be available to sign-up for this appointment.</inlineHelpText>
    <label>Number Appointments per Month</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/C501_Appointment_Schedule__c/fields/Scheduled_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_End_Time__c</fullName>
    <label>Scheduled End Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

src/main/default/objects/C501_Appointment_Schedule__c/fields/Scheduled_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Start_Date_Time__c</fullName>
    <label>Scheduled Start Date &amp; Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/classes/C501_AppointmentScheduleTriggerTest.cls
@isTest
public with sharing class C501_AppointmentScheduleTriggerTest {

	@isTest
	private static void testUpdateAppointmentScheduleTrigger() {

		// Trigger Insert
		C501_Appointment_Schedule__c appointmentSchedule = new C501_Appointment_Schedule__c(
			Name = 'C501_Appointment_Schedule__c.Name',
			Scheduled_Start_Date_Time__c = DateTime.now(),
			Scheduled_End_Time__c = DateTime.now().addHours(1).time(),
			Number_Appointments_per_15_min_interval__c = 4,
			Enable__c = false,
			Number_Appointments_per_Month__c = 10
		);
		insert appointmentSchedule;

		C501_Appointment__c appointment = new C501_Appointment__c(
			Name = 'C501_Appointment__c.Name',
			Available_Time__c = DateTime.now(),
			Date__c = system.today(),
			Time__c = '10:00 AM',
			Enable__c = true,
			Maximum_Scheduled_Appointments__c = 1,
			Appointment_Schedule__c = appointmentSchedule.Id
		);
		insert appointment;

		// Trigger Update
		appointmentSchedule.Enable__c = true;
		update appointmentSchedule;

		// Trigger Delete
		delete appointmentSchedule;
	}
}